# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms
#

prev = 1
curr = 2
nxt = 0
sum = 2
while(nxt < 4000000)
  nxt = prev + curr
  sum += nxt if nxt.even?
  prev = curr
  curr = nxt
end

puts sum

# Answer: 4613732
